[package]
name = "Website_Checker"
version = "0.1.0"
edition = "2024"

[lib]
name = "website_checker"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["tls"] }